### ISSUE TITLE
LPIPS metric is random

### ISSUE THREAD

**Issue by Kepnu4** [MichiganCOG/video-inpainting-evaluation#3]
LPIPS backbone is initialized with random weights for some reason. This result in random result for lpips metric

https://github.com/MichiganCOG/video-inpainting-evaluation/blob/public/src/lpips/networks_basic.py#L80

**Comment by rszeto** [comment]
Hi @Kepnu4,

Terribly sorry for the late response and the error with the LPIPS metric. I've fixed this in commit d339a126b5f3ebd574c6414e7df73af1697102ea. Feel free to reach out if you see other issues.
