### ISSUE TITLE
LPIPS metrics is wrong

### ISSUE THREAD

**Issue by muchen12** [MichiganCOG/video-inpainting-evaluation#4]
I am sorry to bother you.
Thank you for your contribution to the integration. However, it is also important to note that this error will have disastrous consequences for other researchers who want to use your work for algorithm evaluation.

**Comment by rszeto** [comment]
Hi @muchen12,

Terribly sorry for the late response and the error with the LPIPS metric. I've fixed this in commit d339a126b5f3ebd574c6414e7df73af1697102ea. Feel free to reach out if you see other issues.
